In [100]:
import cv2
import numpy as np

In [155]:
img = cv2.pyrDown(cv2.imread('data/2.jpg', cv2.IMREAD_UNCHANGED))
imgray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

In [156]:
# threshold image
ret, threshed_img = cv2.threshold(imgray, 127, 255, cv2.THRESH_BINARY)

In [157]:
# find contours and get the external one
contours, hier = cv2.findContours(threshed_img, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

#image, contours, hier = cv2.findContours(threshed_img, cv2.RETR_TREE,
#                cv2.CHAIN_APPROX_SIMPLE)

In [158]:
# with each contour, draw boundingRect in green
# a minAreaRect in red and
# a minEnclosingCircle in blue
arr = np.empty((0,2), int)
for c in contours:
    ## get the bounding rect
    # x, y, w, h = cv2.boundingRect(c)
    ## draw a green rectangle to visualize the bounding rect
    # cv2.rectangle(img, (x, y), (x+w, y+h), (0, 255, 0), 2)

    # get the min area rect
    rect = cv2.minAreaRect(c)
    box = cv2.boxPoints(rect)
    # convert all coordinates floating point values to int
    box = np.int0(box)
    arr = np.append(arr, box, axis = 0)
    # draw a red 'nghien' rectangle
    cv2.drawContours(img, [box], 0, (0, 0, 255))
    #arr = np.append(arr, np.array(box), axis = 0)
    #arr = np.append(arr, np.array(box))
    print(box)
    
    
#     # finally, get the min enclosing circle
#     (x, y), radius = cv2.minEnclosingCircle(c)
#     # convert all values to int
#     center = (int(x), int(y))
#     radius = int(radius)
#     # and draw the circle in blue
#     img = cv2.circle(img, center, radius, (255, 0, 0), 2)

print(len(contours))
print(arr[:4])
print(arr[4:])
print(arr[:4].mean(axis=0))
print(arr[4:].mean(axis=0))
arr_x = arr[:4].mean(axis=0)
arr_x = np.int0(arr_x)
arr_x

[[  0 105]
 [ 68 105]
 [ 68 158]
 [  0 158]]
[[ 53   0]
 [140   0]
 [140  50]
 [ 53  50]]
2
[[  0 105]
 [ 68 105]
 [ 68 158]
 [  0 158]]
[[ 53   0]
 [140   0]
 [140  50]
 [ 53  50]]
[ 34.  131.5]
[96.5 25. ]


array([ 34, 131], dtype=int64)

In [159]:
# cv2.drawContours(img, contours, -1, (255, 255, 0), 1)

cv2.imshow("contours", img)

cv2.imshow("contours", img)

while True:
    key = cv2.waitKey(1)
    if key == 27: #ESC key to break
        break

cv2.destroyAllWindows()

In [160]:
for c in contours:
    print(box)

[[ 53   0]
 [140   0]
 [140  50]
 [ 53  50]]
[[ 53   0]
 [140   0]
 [140  50]
 [ 53  50]]


In [161]:
red = (0,0,255)
x = arr_x[0]
y = arr_x[1]
cv2.line(img, (x,y), (x,y), red, 5)
cv2.imshow("contour", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [132]:
arr_x[1]

102